<?php

namespace Entities\EntitiesAdminBundle\Repository;

/**
 * ActeDentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActeDentaireRepository extends \Doctrine\ORM\EntityRepository
{
}
