<?php

namespace Entities\EntitiesAdminBundle\Repository;

/**
 * AssuranceCabinetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssuranceCabinetRepository extends \Doctrine\ORM\EntityRepository
{
}
