<?php

namespace Entities\EntitiesAdminBundle\Repository;

/**
 * ServiceEmployeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceEmployeRepository extends \Doctrine\ORM\EntityRepository
{
}
