<?php

namespace Entities\EntitiesAdminBundle\Repository;

/**
 * ServiceCabinetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceCabinetRepository extends \Doctrine\ORM\EntityRepository
{
}
