<?php

namespace SecureBundle\Repository;

/**
 * MenuDroitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuDroitRepository extends \Doctrine\ORM\EntityRepository
{
}
