<?php

namespace SecureBundle\Repository;

/**
 * ObjetDroitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObjetDroitRepository extends \Doctrine\ORM\EntityRepository
{
}
