<?php

namespace SecureBundle\Repository;

/**
 * UserGroupeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserGroupeRepository extends \Doctrine\ORM\EntityRepository
{
}
