<?php

namespace Entities\EntitiesCliniqueBundle\Repository;

/**
 * GespaFamilleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GespaFamilleRepository extends \Doctrine\ORM\EntityRepository
{
}
