<?php

namespace Entities\EntitiesCliniqueBundle\Repository;

/**
 * GespaCorrespondantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GespaCorrespondantRepository extends \Doctrine\ORM\EntityRepository
{
}
