<?php

namespace Entities\EntitiesCliniqueBundle\Repository;

/**
 * GespaPatientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GespaPatientRepository extends \Doctrine\ORM\EntityRepository
{
}
