<?php

namespace Entities\EntitiesAdminBundle\Repository;

/**
 * CabinetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CabinetRepository extends \Doctrine\ORM\EntityRepository
{
}
