<?php

namespace Entities\EntitiesAdminBundle\Repository;

/**
 * PosteOccuperRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PosteOccuperRepository extends \Doctrine\ORM\EntityRepository
{
}
